# Generated by Django 3.2.18 on 2023-04-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymate', '0005_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
