# Generated by Django 3.2.18 on 2023-05-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymate', '0012_auto_20230424_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_choosen',
            field=models.BooleanField(default=False),
        ),
    ]
